apiVersion: v2
name: nginx-multiple
description: A Helm chart to deploy multiple nginx deployments, each with 1 pod
version: 0.1.2
appVersion: "1.25.0"
dependencies:
  - name: common
    version: "2.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"
