{{- range $i := until (int .Values.deploymentCount) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-{{ $i }}
  labels:
    app.kubernetes.io/name: nginx-multiple
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-multiple
      app.kubernetes.io/instance: {{ $.Release.Name }}-{{ $i }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-multiple
        app.kubernetes.io/instance: {{ $.Release.Name }}-{{ $i }}
    spec:
      containers:
        - name: nginx
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - containerPort: 80
{{- end }}
