{{- $count := .Values.deploymentCount }}
{{- range $i := until $count }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-{{ $i }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-{{ $i }}
  template:
    metadata:
      labels:
        app: nginx-{{ $i }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
{{- end }}
