apiVersion: v1
entries:
  apache:
  - annotations:
      category: Infrastructure
      images: |
        - name: apache
          image: docker.io/bitnami/apache:2.4.63-debian-12-r16
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r11
        - name: git
          image: docker.io/bitnami/git:2.50.0-debian-12-r0
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 11.3.16
    created: "2025-06-19T07:15:18.629524404Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache HTTP Server is an open-source HTTP server. The goal of this
      project is to provide a secure, efficient and extensible server that provides
      HTTP services in sync with the current HTTP standards.
    digest: 7993478636100a3c250d67a34fc4ddcd490b879a293970bcdf0cb972f74cdd20
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/apache/img/apache-stack-220x234.png
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: apache
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/apache
    urls:
    - https://portainer.github.io/test-public-repo/helm/apache/apache-11.3.16.tgz
    version: 11.3.16
  - annotations:
      category: Infrastructure
      images: |
        - name: apache
          image: docker.io/bitnami/apache:2.4.63-debian-12-r16
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r11
        - name: git
          image: docker.io/bitnami/git:2.49.0-debian-12-r10
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 11.3.15
    created: "2025-06-19T07:15:18.627338795Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache HTTP Server is an open-source HTTP server. The goal of this
      project is to provide a secure, efficient and extensible server that provides
      HTTP services in sync with the current HTTP standards.
    digest: 0ffbf78556ea4285dc588a6f253fb5b19c4ef376830f965326af880566e46873
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/apache/img/apache-stack-220x234.png
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: apache
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/apache
    urls:
    - https://portainer.github.io/test-public-repo/helm/apache/apache-11.3.15.tgz
    version: 11.3.15
  - annotations:
      category: Infrastructure
      images: |
        - name: apache
          image: docker.io/bitnami/apache:2.4.63-debian-12-r16
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r11
        - name: git
          image: docker.io/bitnami/git:2.49.0-debian-12-r9
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 11.3.14
    created: "2025-06-19T07:15:18.625130134Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache HTTP Server is an open-source HTTP server. The goal of this
      project is to provide a secure, efficient and extensible server that provides
      HTTP services in sync with the current HTTP standards.
    digest: a9498b6f91fb6ed9ea616fdc3198cea5e283762e857fe392f6f759151e33de5a
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/apache/img/apache-stack-220x234.png
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: apache
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/apache
    urls:
    - https://portainer.github.io/test-public-repo/helm/apache/apache-11.3.14.tgz
    version: 11.3.14
  - annotations:
      category: Infrastructure
      images: |
        - name: apache
          image: docker.io/bitnami/apache:2.4.63-debian-12-r16
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r9
        - name: git
          image: docker.io/bitnami/git:2.49.0-debian-12-r9
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 11.3.13
    created: "2025-06-19T07:15:18.622191276Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache HTTP Server is an open-source HTTP server. The goal of this
      project is to provide a secure, efficient and extensible server that provides
      HTTP services in sync with the current HTTP standards.
    digest: c841ae07ce00e8f21a796ae8adb622eb18e10e65da55dcbdd74959b707ec04a9
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/apache/img/apache-stack-220x234.png
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: apache
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/apache
    urls:
    - https://portainer.github.io/test-public-repo/helm/apache/apache-11.3.13.tgz
    version: 11.3.13
  - annotations:
      category: Infrastructure
      images: |
        - name: apache
          image: docker.io/bitnami/apache:2.4.63-debian-12-r16
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r9
        - name: git
          image: docker.io/bitnami/git:2.49.0-debian-12-r8
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 11.3.12
    created: "2025-06-19T07:15:18.619946678Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache HTTP Server is an open-source HTTP server. The goal of this
      project is to provide a secure, efficient and extensible server that provides
      HTTP services in sync with the current HTTP standards.
    digest: bf7ac88f85abf26b784f94e96c52975285656231374900c0c71074dc68ef6725
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/apache/img/apache-stack-220x234.png
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: apache
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/apache
    urls:
    - https://portainer.github.io/test-public-repo/helm/apache/apache-11.3.12.tgz
    version: 11.3.12
  - annotations:
      category: Infrastructure
      images: |
        - name: apache
          image: docker.io/bitnami/apache:2.4.63-debian-12-r16
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r7
        - name: git
          image: docker.io/bitnami/git:2.49.0-debian-12-r8
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 11.3.11
    created: "2025-06-19T07:15:18.617695707Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache HTTP Server is an open-source HTTP server. The goal of this
      project is to provide a secure, efficient and extensible server that provides
      HTTP services in sync with the current HTTP standards.
    digest: 4aecb512d3d61607461e815c01dd7bafad09314961452e9ee9d9f5412de9baf3
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/apache/img/apache-stack-220x234.png
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: apache
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/apache
    urls:
    - https://portainer.github.io/test-public-repo/helm/apache/apache-11.3.11.tgz
    version: 11.3.11
  - annotations:
      category: Infrastructure
      images: |
        - name: apache
          image: docker.io/bitnami/apache:2.4.63-debian-12-r14
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r6
        - name: git
          image: docker.io/bitnami/git:2.49.0-debian-12-r7
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 11.3.10
    created: "2025-06-19T07:15:18.614496548Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache HTTP Server is an open-source HTTP server. The goal of this
      project is to provide a secure, efficient and extensible server that provides
      HTTP services in sync with the current HTTP standards.
    digest: 04aeb0907af2e996e4945a37250e0f4d9b497d768cb0259634d60e801c511949
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/apache/img/apache-stack-220x234.png
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: apache
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/apache
    urls:
    - https://portainer.github.io/test-public-repo/helm/apache/apache-11.3.10.tgz
    version: 11.3.10
  - annotations:
      category: Infrastructure
      images: |
        - name: apache
          image: docker.io/bitnami/apache:2.4.63-debian-12-r13
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r6
        - name: git
          image: docker.io/bitnami/git:2.49.0-debian-12-r7
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 11.3.9
    created: "2025-06-19T07:15:18.637376212Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache HTTP Server is an open-source HTTP server. The goal of this
      project is to provide a secure, efficient and extensible server that provides
      HTTP services in sync with the current HTTP standards.
    digest: 474943d057be882c3129696035a0bfddb91ecac5131f1f23ec6a94af70d6c050
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/apache/img/apache-stack-220x234.png
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: apache
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/apache
    urls:
    - https://portainer.github.io/test-public-repo/helm/apache/apache-11.3.9.tgz
    version: 11.3.9
  - annotations:
      category: Infrastructure
      images: |
        - name: apache
          image: docker.io/bitnami/apache:2.4.63-debian-12-r10
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r5
        - name: git
          image: docker.io/bitnami/git:2.49.0-debian-12-r6
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 11.3.8
    created: "2025-06-19T07:15:18.634717699Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache HTTP Server is an open-source HTTP server. The goal of this
      project is to provide a secure, efficient and extensible server that provides
      HTTP services in sync with the current HTTP standards.
    digest: 5535de2a7a949ee1030f58788f6e057ee9cb2692f7a5cccdc9072f5640ccc0af
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/apache/img/apache-stack-220x234.png
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: apache
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/apache
    urls:
    - https://portainer.github.io/test-public-repo/helm/apache/apache-11.3.8.tgz
    version: 11.3.8
  - annotations:
      category: Infrastructure
      images: |
        - name: apache
          image: docker.io/bitnami/apache:2.4.63-debian-12-r10
        - name: apache-exporter
          image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r4
        - name: git
          image: docker.io/bitnami/git:2.49.0-debian-12-r5
      licenses: Apache-2.0
      tanzuCategory: service
    apiVersion: v2
    appVersion: 11.3.7
    created: "2025-06-19T07:15:18.632434669Z"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Apache HTTP Server is an open-source HTTP server. The goal of this
      project is to provide a secure, efficient and extensible server that provides
      HTTP services in sync with the current HTTP standards.
    digest: 1ec41d1b692a51524aa6941b5d3a29c5d1f03b018bd9ea66d315b262cbc7a62a
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/apache/img/apache-stack-220x234.png
    keywords:
    - apache
    - http
    - https
    - www
    - web
    - reverse proxy
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: apache
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/apache
    urls:
    - https://portainer.github.io/test-public-repo/helm/apache/apache-11.3.7.tgz
    version: 11.3.7
generated: "2025-06-19T07:15:18.611999256Z"
